spring.application.name=Application_Properties
payment-gateway.type = Paytm
payment-gateway.retryCount = 6;

payment-properties.type = Upi
payment-properties.retrycount = 5
payment-properties.enabled = true
payment-properties.timeout = 30000